config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources "books", only: [:index, :show, :new, :create, :destroy] do
    resources "reservations", only: [:create, :show]
  end
  resources "reservations", only: [:new, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reservations, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :search_by_title_and_author_and_genre,
    against: [ :title, :author, :genre ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def image_creator(genre)
    case genre
    when "horror"
      return "skull.png"
    when "love"
      return "love.png"
    when "comedy"
      return "comedy.png"
    when "super natural"
      return "supernatural.png"
    else
      return "alien.png"
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query].present?
      @books = Book.search_by_title_and_author_and_genre(params[:query])
    else
      @books = Book.all
    end

    @markers = @books.geocoded.map do |book|
      {
        lat: book.latitude,
        lng: book.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {book: book}),
        marker_html: render_to_string(partial: "marker")
      }
    end

  end

  def show
    @book = Book.find(params[:id])
    @reservation = Reservation.new
    @bookmarkers = [@book.latitude, @book.longitude]

    @markers =
      {
        lat: @book.latitude,
        lng: @book.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {book:  @book}),
        marker_html: render_to_string(partial: "minimarker")
      }
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to books_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :photo, :author, :genre, :synopsis, :release_date, :address)
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
    @books = Book.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = current_user.reservations
  end

  def show
    @reservation = Reservation.find(params[:id])
    @book = @reservation.book
  end

  def new
    @reservation = Reservation.new
    @book = Book.find(params[:book_id])
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @book = Book.find(params[:book_id])
    @reservation.book = @book
    @reservation.user = current_user
    if @reservation.save!
      redirect_to book_reservation_path(@book, @reservation), notice: 'Congratulations 🎉 You have reserved this Book!'
    else
      render :new
    end
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to reservations_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:reservation_start, :reservation_end, :user_id, :book_id)
  end

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_info_window.html.erb
<h2><%= book.title %></h2>
<p><%= book.address %></p>

app/views/books/_marker.html.erb
<%= image_tag "bat.png", height: 50, width: 50, alt: "Bat Logo" %>

app/views/books/_minimarker.html.erb
<%= image_tag "bat.png", height: 50, width: 50, alt: "Bat Logo" %>

app/views/books/index.html.erb
<div class="map-container mt-5"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
</div>

<div class="container">
  <%= form_with url: books_path, method: :get, class: "d-flex justify-content-center mt-5" do %>
    <%= text_field_tag :query,
                       params[:query],
                       class: "form-control search-bar",
                       placeholder: "Find a book" %>
    <%= submit_tag "Search", class: "btn" %>
  <% end %>

  <div class="book-list-container mt-5">
    <% @books.each do |book| %>
      <div class="book-card hvr-grow">
        <div class="book-content">
          <div class="book-title">
          <%= image_tag book.image_creator(book.genre), class: "mb-4" %>
            <h4><%= book.title %> </h4>
            <p> <%= book.author %> </p>
             <%= link_to "Details", book_path(book) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/books/new.html.erb
<div class="container">

  <div class="row">
    <h2 class="heading-color mt-4" style='text-align: center;margin:0;'>Share your Spooks here</h2>
    <div class="custom-wrapper">
        <div class="col-6">
        <%= simple_form_for(@book) do |f| %>

            <%= f.input :title %>
            <%= f.input :author %>
            <%= f.input :genre %>
            <%= f.input :release_date %>
            <%= f.input :synopsis %>
            <%= f.input :address %>
            <%= f.input :photo, as: :file, class: "customfile" %>
            <%= f.submit "Upload", class: "upload-button" %>


        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="spookies">
    <h2 class="heading-color">Reserve your Spookieesss</h2>
    <%= image_tag @book.image_creator(@book.genre), class: "mb-4" %>
  </div>

  <div class="card-show">
    <div class="row">
      <div class="col-6">
        <% if @book.photo.attached? %>
          <%= cl_image_tag @book.photo.key ? @book.photo.key : "book_icon.png", height: 300, width: 400, crop: :fill, style: "background-color: white; width: 100%; height:100%;" %>
        <% else %>
          <%= image_tag(["book1.jpg", "book2.jpg", "book3.jpg"].sample) %>
        <% end %>
      </div>
      <div class="col-6">
        <p class="show-title">Title</p>
        <div class="info-box"><p><%= @book.title %></p></div>
        <p class="show-title">Author</p>
        <div class="info-box"><p><%= @book.author %></p></div>
        <p class="show-title">Genre</p>
        <div class="info-box"><p><%= @book.genre %></p></div>
        <p class="show-title">Release Date</p>
        <div class="info-box"><p><%= @book.release_date %></p></div>
        <p class="show-title">Synopsis</p>
        <div class="info-box synopsis"><p><%= @book.synopsis %></p></div>
      </div>
    </div>
  </div>

  <div class="show-bottom">
    <div class="map-container-2" style="width: 700px; height: 300px;"
      data-controller="singlemap"
      data-singlemap-markers-value="<%= @markers.to_json %>"
      data-singlemap-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
    </div>

    <div class="calendar simple-form-custom-dillon">
      <%= simple_form_for  [@book, @reservation], data: { controller: 'flatpickr' } do |f| %>
        <%= f.input :reservation_start, as: :string, placeholder: 'start date', input_html: { data: { flatpickr_target: "reservation_start" } } %>
        <%= f.input :reservation_end, as: :string, placeholder: 'end date', input_html: { data: { flatpickr_target: "reservation_end" } } %>
        <%= f.submit "confirm your reservation", id: 'sweet-alert-demo'%>
      <% end %>
    </div>
  </div>

  <div class="button-container mt-4" style="align-items: right;">
    <%= link_to "Back to Books", books_path, class: "custombutton" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSharing</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
      <%= render "shared/navbar" %>
    <div class="main-content-wrapper">

    <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  <footer class="footer">
    <p> <%= link_to "Terms and conditons" %></p>
    <p> <%= link_to "© 2020 Career Karma" %></p>
  </footer>
  </body>

</html>

app/views/pages/home.html.erb
<div class="background">
  <div class="home-banner">
    <div class="home-banner-content">
      <h1>SpookSharing</h1>
      <p>
        Don't be greedy, share your spooks
      </p>
    </div>
  </div>

  <div class ="home-cta heading-color">
    <%= link_to "Reserve", books_path(@books) %>
    <%= link_to "Share one of your books", new_book_path(@book) %>
  </div>

  <div class="top-books">
   <h3 class="reservation-heading">These are our top spooks</h3>
   <div class="book-list-container mt-5">
    <% @books.first(4).each do |book| %>
      <div class="home-book-card">

        <div class="book-content">
          <div class="book-title pb-4">
          <%= image_tag book.image_creator(book.genre), class: "mb-4" %>
            <h4><%= book.title %> </h4>
            <p> <%= book.author %> </p>
             <%= link_to "Details", book_path(book) %>
          </div>
        </div>

      </div>
    <% end %>
  </div>
   </div>
</div>



<div class="how-it-works">
  <div class="how-it-content">
  <%= image_tag "find.png" %>
  <h4>Find your pick</h4>
    <p>
      We often do book sharing, because it’s not necessary to buy a new book just to read it once.
      After you read a book, it’ll take a lot of space and you don’t know where to put the book.
    </p>
  </div>
  <div class="how-it-content">
  <%= image_tag "reserve.png" %>
  <h4>Reserve</h4>
    <p>
      Sharing is the easiest way to get rid of it.
      In our opinion it’s a great way to help our environment,
      and we would definitely recommend it to everyone!
    </p>
  </div>
  <div class="how-it-content">
  <%= image_tag "order.png" %>
  <h4>Order</h4>
    <p>
      As another word for book sharing we also use book change,
      book swapping or book crossing. The word book sharing was used
      in 2000 for the first time (USA). But we guess people already used it before 2000.
      </p>
  </div>
  <div class="how-it-content">
  <%= image_tag "creepy-ghost.png" %>
  <h4>Deliver</h4>
    <p>
      Book sharing contains a lot of advantages:
      Book sharing is very cheap. That’s why people get animated to read.
      Through book sharing you get to know different authors and stories.
    </p>
  </div>
</div>

app/views/reservations/index.html.erb
<h2 class="reservation-heading heading-color">Spooks you have reserved</h2>
  <div class="reservation-list-container">
    <% @reservations.each do |reservation| %>
      <div class="reservation-card">
        <% if reservation.book.photo.attached? %>

          <% # <%= image_tag %>

          <%= cl_image_tag reservation.book.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <%= image_tag(["blood_book.jpg"].sample) %>
        <% end %>
        <div class="book-content-res">
          <div class="book-title">
            <p> <%= reservation.book.title %> </p>
            <p> <%= reservation.book.author %> </p>
          </div>



          <div class="button-container-res">
            <%= link_to "Delete", reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "delete-res-button" %>
            <%= link_to "Details", book_reservation_path(reservation.book, reservation), class: "delete-res-button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/reservations/show.html.erb
<div class="container">
  <div class="spookies">
    <h2 class="reservation-heading heading-color">Your Resevation is</h2>
  </div>

  <div class="card-show">
    <div class="row">
      <div class="col-6">
        <% if @book.photo.attached? %>
          <%= cl_image_tag @book.photo.key ? @book.photo.key : "book_icon.png", height: 300, width: 400, crop: :fill, style: "background-color: white; width: 100%; height:100%;" %>
        <% else %>
          <%= image_tag(["book1.jpg", "book2.jpg", "book3.jpg"].sample) %>
        <% end %>
      </div>
      <div class="col-6">
        <p class="show-title">Title</p>
        <div class="info-box"><p><%= @book.title %></p></div>
        <p class="show-title">Author</p>
        <div class="info-box"><p><%= @book.author %></p></div>
        <p class="show-title">Genre</p>
        <div class="info-box"><p><%= @book.genre %></p></div>
        <p class="show-title">Release Date</p>
        <div class="info-box"><p><%= @book.release_date %></p></div>
        <p class="show-title">Synopsis</p>
        <div class="info-box synopsis"><p><%= @book.synopsis %></p></div>
      </div>
    </div>
  </div>

  <div class="show-bottom">
    <div class="map-container-2" style="width: 700px; height: 300px;"
      data-controller="singlemap"
      data-singlemap-markers-value="<%= @markers.to_json %>"
      data-singlemap-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
    </div>

    <div class="reserved">
      <h3>Reserved</h3>
      <p>from:</p>
      <p style="color: white;"><%= @reservation.reservation_start %></p>
      <p>to</p>
      <p style="color: white;"><%= @reservation.reservation_end %></p>
    </div>
  </div>


  <div class="button-container mt-4" style="align-items: right;">
    <%= link_to "Back to Books", books_path, class: "custombutton" %>
    <p style="color: #0c0b0a;">oops</p>
    <%= link_to "All reservations", reservations_path, class: "custombutton" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "book_icon.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <% # <%= link_to "Login", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <% # <%= link_to "search", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "My reservations", reservations_path %>
            <%= image_tag "account.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% #= link_to "Login", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>